data_ingestion:
  bucket_name: "2-mlops-64"
  bucket_file_names:
    - "anime.csv"
    - "anime_with_synopsis.csv"
    - "animelist.csv"

model:
  embedding_size: 128
  loss: binary_crossentropy
  optimizer: Adam
  metrics: ["mae","mse"]
